# Generated by Django 3.1.5 on 2021-01-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horseId', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('breed', models.CharField(max_length=255)),
                ('food', models.CharField(max_length=255)),
                ('disease', models.CharField(max_length=255)),
            ],
        ),
    ]
