# Generated by Django 3.1.5 on 2021-01-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='horseId',
        ),
    ]
