ALTER DATABASE Horse_shelter SET ALLOW_SNAPSHOT_ISOLATION ON
use Horse_shelter
go

WAITFOR DELAY '00:00:10'
BEGIN TRAN
UPDATE versions SET version_number = 5 WHERE Vid = 1
WAITFOR DELAY '00:00:10'
COMMIT TRAN