# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from qtpy import QtWidgets,QtCore

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.solutionShowWidget = QtWidgets.QListWidget(self.centralwidget)
        self.solutionShowWidget.setGeometry(QtCore.QRect(405, 71, 361, 481))
        self.solutionShowWidget.setObjectName("solutionShowWidget")
        self.inputMatrixDim = QtWidgets.QLineEdit(self.centralwidget)
        self.inputMatrixDim.setGeometry(QtCore.QRect(140, 0, 113, 22))
        self.inputMatrixDim.setObjectName("inputMatrixDim")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 111, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(420, 40, 271, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 160, 271, 16))
        self.label_3.setObjectName("label_3")
        self.eaAlgButton = QtWidgets.QPushButton(self.centralwidget)
        self.eaAlgButton.setGeometry(QtCore.QRect(10, 180, 161, 28))
        self.eaAlgButton.setObjectName("eaAlgButton")
        self.hillAlgButton = QtWidgets.QPushButton(self.centralwidget)
        self.hillAlgButton.setGeometry(QtCore.QRect(10, 220, 241, 28))
        self.hillAlgButton.setObjectName("hillAlgButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.label_4.setObjectName("label_4")
        self.inputMutation = QtWidgets.QLineEdit(self.centralwidget)
        self.inputMutation.setGeometry(QtCore.QRect(140, 30, 113, 22))
        self.inputMutation.setObjectName("inputMutation")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 131, 16))
        self.label_5.setObjectName("label_5")
        self.inputCrossOver = QtWidgets.QLineEdit(self.centralwidget)
        self.inputCrossOver.setGeometry(QtCore.QRect(140, 60, 113, 22))
        self.inputCrossOver.setObjectName("inputCrossOver")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 90, 111, 16))
        self.label_6.setObjectName("label_6")
        self.inputPopulation = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPopulation.setGeometry(QtCore.QRect(140, 90, 113, 22))
        self.inputPopulation.setObjectName("inputPopulation")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 120, 111, 16))
        self.label_7.setObjectName("label_7")
        self.inputTrials = QtWidgets.QLineEdit(self.centralwidget)
        self.inputTrials.setGeometry(QtCore.QRect(140, 120, 113, 22))
        self.inputTrials.setObjectName("inputTrials")
        self.validateTestButton = QtWidgets.QPushButton(self.centralwidget)
        self.validateTestButton.setGeometry(QtCore.QRect(250, 180, 93, 28))
        self.validateTestButton.setObjectName("validateTestButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "matrix dimensions:"))
        self.label_2.setText(_translate("MainWindow", "The graph will be shown here:"))
        self.label_3.setText(_translate("MainWindow", "Now choose a method to run:"))
        self.eaAlgButton.setText(_translate("MainWindow", "EvolutionaryAlgorithm"))
        self.hillAlgButton.setText(_translate("MainWindow", " HillClimbingAlgorithm(using greedy)"))
        self.label_4.setText(_translate("MainWindow", "mutation probabilty:"))
        self.label_5.setText(_translate("MainWindow", "crossover probability:"))
        self.label_6.setText(_translate("MainWindow", "population size:"))
        self.label_7.setText(_translate("MainWindow", "number of trials:"))
        self.validateTestButton.setText(_translate("MainWindow", "Validate Test"))

